name: com.banorteEduApp.app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_svg: ^2.0.7  # Asegúrate de usar la versión más reciente
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_database: ^11.1.4
  http: ^1.1.0
  google_auth: ^0.0.3
  googleapis: ^13.2.0
  cloud_firestore: ^5.4.4
  dialogflow_grpc: ^0.2.9


  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/BackgroundRed.png
    - assets/images/BackgroundRed.svg
    - assets/images/logo.png
    - assets/agent.html

  fonts:
    - family: Gotham
      fonts:
        - asset: assets/fonts/Gotham-Bold.otf
          weight: 700
  